### ISSUE TITLE
Support Jetty 11.0.9

### ISSUE THREAD

**Issue by Milton-Ch** [hantsy/jakartaee9-starter-boilerplate#237]
We are using Arquillian 1.7.0.Alpha10 and Jetty 11.0.9, inside our web app we have some pieces using JSP and Resteasy, however currently JSP works, but none of our rest endpoints are working, after Arquillian starts our server, all of them are returning not found.

![image](https://user-images.githubusercontent.com/86965029/168079175-0c9f9b0f-4a3d-4f82-8fbd-cb07b24e3239.png)

It's similar or related to this another article: https://www.javafixing.com/2021/10/fixed-jetty-11-doesn-detect-jakarta.html

We were trying multiple configs in web.xml, arquillian.xml and jetty xml files, however we couldn't get it working.

Do we have some running example that we can follow using Jetty 11?

**Comment by hantsy** [comment]
This project is for full Jakarta EE support, for servlet containers, go to https://github.com/hantsy/jakartaee9-servlet-starter-boilerplate
