### ISSUE TITLE
Failure to find org.apache.tomee.jakarta:apache-tomee:zip:plume:9.0.0.RC1

### ISSUE THREAD

**Issue by abstract-thinking** [hantsy/jakartaee9-starter-boilerplate#292]
I am afraid that Tomee has been removed from the repository, can that be?

INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.188 s
[INFO] Finished at: 2023-01-16T14:36:49+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.tomee.maven:tomee-maven-plugin:9.0.0.RC1:run (default-cli) on project jakartaee9-starter-boilerplate: Execution default-cli of goal org.apache.tomee.maven:tomee-maven-plugin:9.0.0.RC1:run failed: Failure to find org.apache.tomee.jakarta:apache-tomee:zip:plume:9.0.0.RC1 in https://jakarta.oss.sonatype.org/content/repositories/staging/ was cached in the local repository, resolution will not be reattempted until the update interval of sonatype-nexus-staging has elapsed or updates are forced
[ERROR] 
[ERROR] Try downloading the file manually from the project website.
[ERROR] 
[ERROR] Then, install it using the command: 
[ERROR]     mvn install:install-file -DgroupId=org.apache.tomee.jakarta -DartifactId=apache-tomee -Dversion=9.0.0.RC1 -Dclassifier=plume -Dpackaging=zip -Dfile=/path/to/file
[ERROR] 
[ERROR] Alternatively, if you host your own repository you can deploy the file there: 
[ERROR]     mvn deploy:deploy-file -DgroupId=org.apache.tomee.jakarta -DartifactId=apache-tomee -Dversion=9.0.0.RC1 -Dclassifier=plume -Dpackaging=zip -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]
[ERROR] 
[ERROR] 
[ERROR]   org.apache.tomee.jakarta:apache-tomee:zip:9.0.0.RC1
[ERROR] 
[ERROR] from the specified remote repositories:
[ERROR]   sonatype-nexus-staging (https://jakarta.oss.sonatype.org/content/repositories/staging/, releases=true, snapshots=false),
[ERROR]   payara-nexus (https://nexus.payara.fish/repository/payara-artifacts/, releases=true, snapshots=true),
[ERROR]   central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false),
[ERROR]   apache (https://repository.apache.org/content/repositories/snapshots/, releases=false, snapshots=true)

**Comment by hantsy** [comment]
Use `org.apache.tomee` instead in the RC and final version. It seems the `org.apache.tomee.jakarta` only occurs in the milestones.
